name: Main workflow

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2020.04.05'

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: lein deps

      - name: Run checks
        run: make checks

      - name: Run tests
        run: make test
